# Generated by Django 5.2 on 2025-07-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_type', models.CharField(max_length=50)),
                ('skill_name', models.CharField(max_length=100)),
                ('certificate_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='certificates/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'certificate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'skill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('ss_id', models.AutoField(primary_key=True, serialize=False)),
                ('hard_skill', models.CharField(blank=True, max_length=255)),
                ('soft_skill', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'studentskill',
                'managed': False,
            },
        ),
    ]
